"""Module registry for esp-harness scaffold projects.

Each module knows how to scaffold files into a project, remove them,
and contribute a fragment to the manifest output.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Module:
    name: str
    description: str
    default: bool
    cmake_requires: list[str] = field(default_factory=list)
    _files: dict[str, str] = field(default_factory=dict, repr=False)

    def scaffold(self, project_dir: Path, project_name: str = "") -> list[str]:
        created = []
        for relpath, content in self._files.items():
            rendered = content.replace("__NAME__", project_name)
            full = project_dir / relpath
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(rendered, encoding="utf-8")
            created.append(relpath)
        return created

    def remove(self, project_dir: Path) -> list[str]:
        removed = []
        for relpath in self._files:
            full = project_dir / relpath
            if full.is_file():
                full.unlink()
                removed.append(relpath)
        return removed

    def manifest_fragment(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "default": self.default,
            "cmake_requires": self.cmake_requires,
        }


_MOD_SCENES = Module(
    name="scenes",
    description="LVGL scene framework with lifecycle hooks",
    default=True,
    cmake_requires=["esp-harness-core", "lvgl__lvgl"],
)

_MOD_CONSOLE = Module(
    name="console",
    description="Line-based console protocol (OK:/ERR:/EVT:)",
    default=True,
    cmake_requires=["esp-harness-core"],
)

_MOD_TOAST = Module(
    name="toast",
    description="Fire-and-forget overlay notification",
    default=True,
    cmake_requires=["esp-harness-core"],
)

_MOD_BRIDGE = Module(
    name="bridge",
    description="Python host bridge + hook_dispatch for Claude Code / Cursor",
    default=False,
    _files={
        "bridge/bridge.py": (
            '"""Host bridge — forwards agent hooks to device."""\n'
            "# Generated by esp-harness create. Customize as needed.\n"
            "\n"
            "from __future__ import annotations\n"
            "import argparse\n"
            "import sys\n"
            "\n"
            "def main():\n"
            '    print("[bridge] placeholder — see esp32-agent-dashboard for full implementation")\n'
            "\n"
            'if __name__ == "__main__":\n'
            "    main()\n"
        ),
        "bridge/hook_dispatch.py": (
            '"""Hook dispatcher — forwards Claude Code hooks to bridge."""\n'
            "import json, socket, sys\n"
            "\n"
            "HOST, PORT = '127.0.0.1', 7321\n"
            "\n"
            "def main():\n"
            "    event = sys.argv[1] if len(sys.argv) > 1 else 'raw'\n"
            "    raw = sys.stdin.read().strip()\n"
            "    try:\n"
            "        with socket.create_connection((HOST, PORT), timeout=1.0) as s:\n"
            "            s.sendall((json.dumps({'type': event, 'text': raw}) + '\\n').encode())\n"
            "            print(s.makefile('r').readline().strip() or json.dumps({'continue': True}))\n"
            "    except (ConnectionRefusedError, OSError):\n"
            "        print(json.dumps({'continue': True}))\n"
            "\n"
            'if __name__ == "__main__":\n'
            "    main()\n"
        ),
    },
)

_MOD_HOOKS = Module(
    name="hooks",
    description="Claude Code / Cursor hook configuration snippets",
    default=False,
    _files={
        ".harness/hooks-snippet.json": (
            '{\n'
            '  "hooks": {\n'
            '    "PreToolUse": "python bridge/hook_dispatch.py pre_tool_use",\n'
            '    "PostToolUse": "python bridge/hook_dispatch.py post_tool_use",\n'
            '    "Stop": "python bridge/hook_dispatch.py stop"\n'
            '  }\n'
            '}\n'
        ),
    },
)

_MOD_SIM = Module(
    name="sim",
    description="SDL2 host simulator with visual regression (sim diff)",
    default=False,
    _files={
        "sim/README.md": (
            "# Host Simulator\n\n"
            "Run scenes on your desktop without flashing.\n\n"
            "```bash\n"
            "cd sim && cmake -B build && cmake --build build\n"
            "esp-harness sim snapshot --scene 0 --out check.bmp\n"
            "```\n"
        ),
    },
)

_MOD_OTA = Module(
    name="ota",
    description="WiFi OTA update scaffold with signature verification",
    default=False,
    _files={
        "main/ota/ota_update.h": (
            "#pragma once\n"
            "void ota_check_and_apply(const char *url);\n"
        ),
    },
)

_MOD_PUSH_BANNER = Module(
    name="push-banner",
    description="Top-slide-down tool-event overlay on lv_layer_top",
    default=False,
    cmake_requires=["esp-harness-core"],
    _files={
        "main/push_banner.h": (
            "#pragma once\n"
            "#include <stdint.h>\n"
            "void push_banner_show(const char *tool, const char *hint, uint32_t duration_ms);\n"
            "void push_banner_dismiss(void);\n"
        ),
    },
)

_MOD_BUTTONS = Module(
    name="buttons",
    description="BOOT/USER GPIO button driver with handler registration",
    default=False,
    cmake_requires=["espressif__button"],
)


MODULE_REGISTRY: list[Module] = [
    _MOD_SCENES, _MOD_CONSOLE, _MOD_TOAST,
    _MOD_BRIDGE, _MOD_HOOKS, _MOD_SIM,
    _MOD_OTA, _MOD_PUSH_BANNER, _MOD_BUTTONS,
]


def get_module(name: str) -> Module | None:
    for m in MODULE_REGISTRY:
        if m.name == name:
            return m
    return None


def list_all_modules() -> list[Module]:
    return list(MODULE_REGISTRY)


def default_modules() -> dict[str, bool]:
    return {m.name: m.default for m in MODULE_REGISTRY}
