"""`esp-harness init <name>` — generate a starter ESP-IDF + LVGL project.

The minimum viable project that consumes `aurora-harness`:
  - app_main wiring (NVS / display / console / scene framework)
  - one demo scene
  - CMakeLists pointing at a sibling esp32-harness-showcase clone for the
    aurora-harness component
  - README with the quickstart commands

After running `esp-harness init my-thing`, the user should be able to
`cd my-thing && esp-harness build && esp-harness flash` and see a
"Hello" scene on the device. Everything else is iteration.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from esp_harness.exit_codes import GENERIC_ERROR, OK
from esp_harness.output import Output


# ── template strings ──────────────────────────────────────────────────
#
# __NAME__ is replaced with the project name (kebab-case ok, will be
# C-identifier-cleansed where it appears in symbols).

TOP_CMAKE = """\
# Top-level ESP-IDF project file for __NAME__.
#
# aurora-harness sits in a sibling esp32-harness-showcase repo by
# convention. Override with -DAURORA_HARNESS_DIR=... at cmake time, or
# vendor the component directly into ./components/ for a self-contained
# tree.

cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED AURORA_HARNESS_DIR)
    set(AURORA_HARNESS_DIR ${CMAKE_SOURCE_DIR}/../esp32-harness-showcase/components)
endif()
if(EXISTS "${AURORA_HARNESS_DIR}/aurora-harness")
    list(APPEND EXTRA_COMPONENT_DIRS ${AURORA_HARNESS_DIR})
    message(STATUS "aurora-harness: ${AURORA_HARNESS_DIR}/aurora-harness")
else()
    message(WARNING
        "aurora-harness not found at ${AURORA_HARNESS_DIR}/aurora-harness. "
        "Clone esp32-harness-showcase next to this project, or pass "
        "-DAURORA_HARNESS_DIR=/path/to/showcase/components.")
endif()

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(__NAME__)
"""

MAIN_CMAKE = """\
idf_component_register(
    SRCS
        "__NAME___main.c"
        "scenes/scene_hello.c"
    INCLUDE_DIRS
        "."
        "scenes"
    REQUIRES
        lvgl__lvgl
        aurora-harness
        # Add your board's BSP component here, e.g.:
        # esp32_s3_touch_amoled_2_16
    PRIV_REQUIRES
        nvs_flash
        esp_timer
)
"""

MAIN_C = """\
/*
 * __NAME___main.c — generated by `esp-harness init`.
 *
 * Wires up the standard scaffold: NVS init -> display -> console
 * protocol -> default harness commands -> scene framework -> one demo
 * scene. Replace scene_hello with your own scenes and add more
 * peripherals as needed.
 */

#include "esp_log.h"
#include "nvs_flash.h"

#include "lvgl.h"
#include "bsp/esp-bsp.h"

#include "harness/console_protocol.h"
#include "harness/scene_framework.h"
#include "harness/default_cmds.h"
#include "scenes/scenes.h"

static const char *TAG = "__NAME__";

static void frame_cb(lv_timer_t *t)
{
    (void)t;
    harness_record_frame();
}

void app_main(void)
{
    /* NVS must be up before any subsystem that touches it (WiFi PHY
     * calibration, settings, etc). */
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }

    /* Bring up display + LVGL via the BSP. */
    bsp_display_start();

    /* Console protocol + the default ?stat command. */
    console_protocol_init();
    harness_default_register();

    /* Build the UI under the LVGL lock. */
    bsp_display_lock(-1);

    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

    scene_fw_init(scr);
    scene_fw_register(&scene_hello);

    /* Per-frame tick so ?stat's fps field updates. */
    lv_timer_create(frame_cb, 33, NULL);

    bsp_display_unlock();

    ESP_LOGI(TAG, "ready, %d scene(s)", scene_fw_count());
}
"""

SCENE_HELLO_C = """\
/*
 * scene_hello.c — minimal scene template. Centered label, no animation,
 * no peripheral reads. Copy this file to scene_<name>.c, edit, register
 * in __NAME___main.c.
 */

#include "harness/scene_framework.h"
#include "lvgl.h"

static void hello_init(scene_t *s, lv_obj_t *parent)
{
    (void)s;

    lv_obj_t *label = lv_label_create(parent);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_22, 0);
    lv_obj_set_style_text_color(label, lv_color_hex(0x8FD9FF), 0);
    lv_label_set_text(label, "Hello, aurora-harness");
    lv_obj_center(label);
}

scene_t scene_hello = {
    .id           = "hello",
    .display_name = "I. Hello",
    .accent       = LV_COLOR_MAKE(0x8F, 0xD9, 0xFF),
    .init         = hello_init,
};
"""

SCENES_H = """\
#pragma once
#include "harness/scene_framework.h"

#ifdef __cplusplus
extern "C" {
#endif

extern scene_t scene_hello;

#ifdef __cplusplus
}
#endif
"""

README_MD = """\
# __NAME__

ESP-IDF + LVGL project generated by `esp-harness init`. Consumes the
[`aurora-harness`](https://github.com/Caldis/esp32-harness-showcase/tree/master/components/aurora-harness)
component for console protocol + scene framework.

## Quickstart

```bash
# Auto-discover board on a USB port:
esp-harness port detect

# Build + flash + boot:
esp-harness build
esp-harness flash
esp-harness monitor --seconds 8 --until "ready"

# All-in-one:
esp-harness run --until "ready"
```

## Layout

```
__NAME__/
├── CMakeLists.txt              ESP-IDF top-level project file
├── main/
│   ├── CMakeLists.txt          main component registration
│   ├── __NAME___main.c         app_main + display + scene framework wiring
│   └── scenes/
│       ├── scenes.h
│       └── scene_hello.c       minimal scene template
└── sdkconfig.defaults          recommended starting Kconfig
```

## Adding a new scene

1. Copy `main/scenes/scene_hello.c` to `main/scenes/scene_<name>.c`.
2. Define a fresh `scene_t scene_<name> = { ... };` at the bottom.
3. Add `extern scene_t scene_<name>;` to `main/scenes/scenes.h`.
4. List the new `.c` in `main/CMakeLists.txt` SRCS.
5. `scene_fw_register(&scene_<name>);` in `__NAME___main.c`.

That's it — the scene shows up in `esp-harness console --cmd "scene list"`
automatically.

## Adding a console command

```c
static int cmd_hello(const console_args_t *args) {
    (void)args;
    console_reply_ok("hi");
    return 0;
}

static const console_cmd_t s_cmd_hello = { "?hello", cmd_hello, "say hi" };

void register_my_cmds(void) {
    console_protocol_register(&s_cmd_hello);
}
```

Call `register_my_cmds()` from `app_main` after `console_protocol_init()`.

## Where is aurora-harness?

By default this project expects `esp32-harness-showcase` cloned in
a sibling directory:

```
parent/
├── esp32-harness-showcase/     <-- contains components/aurora-harness/
└── __NAME__/                   <-- you are here
```

Override at build time: `cmake -DAURORA_HARNESS_DIR=/abs/path/components`.

## What you got

- **Scene framework** — a deck of full-screen LVGL views with lifecycle
  hooks. Register scenes once, navigate via console (`scene next` /
  `scene <id>`) or touch.
- **Console protocol** — `OK:` / `ERR:` / `EVT:` framing + multi-line
  payload tags. Universal AI-driveable serial interface.
- **`?stat` command** — fps / heap / scene state as JSON.
- **`?ping` / `?help` / `?reset`** — built-ins.

Add more capabilities by registering more commands and scenes. See
[`aurora-harness/README.md`](https://github.com/Caldis/esp32-harness-showcase/blob/master/components/aurora-harness/README.md)
for the full API.
"""

SDKCONFIG_DEFAULTS = """\
# Recommended starting Kconfig values for an aurora-harness project.
# Most of these are conservative; tune as needed.

# Speed
CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=y
CONFIG_COMPILER_OPTIMIZATION_PERF=y

# LVGL needs PSRAM for full-screen buffers on most boards.
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_SPEED_80M=y

# console_protocol uses USB-Serial-JTAG by default. If you want UART:
#   CONFIG_ESP_CONSOLE_UART_DEFAULT=y
CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=y

# NVS needed for nvs_flash_init() in main.
CONFIG_NVS_ENABLED=y
"""

PARTITIONS_CSV = """\
# Standard factory layout. Bump app size if your binary grows past 6 MB
# or add OTA partitions when you wire up esp_https_ota.
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs,      data, nvs,      0x9000,   0x6000,
phy_init, data, phy,      0xf000,   0x1000,
factory,  app,  factory,  0x10000,  6M,
"""

GITIGNORE = """\
build/
.vscode/
sdkconfig
sdkconfig.old
managed_components/
dependencies.lock
"""


def add_subparser(sub, add_common_flags) -> None:
    p = sub.add_parser(
        "init",
        help="Generate a starter ESP-IDF + LVGL project that uses aurora-harness.",
        description=(
            "Creates a directory <name>/ with a minimal app_main, a 'Hello' "
            "scene, and CMakeLists pointing at a sibling esp32-harness-showcase "
            "clone for the aurora-harness component. Customise from there."
        ),
    )
    p.add_argument("name", help="Project directory to create. Must not exist yet.")
    p.add_argument(
        "--harness-dir", type=Path, default=None,
        help="Override path to the directory holding aurora-harness/. "
             "Default: ../esp32-harness-showcase/components (sibling repo).",
    )
    add_common_flags(p)


def _c_safe_name(name: str) -> str:
    """Make a project name safe for C identifiers: replace -+./ with _."""
    return "".join(c if c.isalnum() else "_" for c in name)


def _write(out: Path, content: str, output: Output) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8", newline="\n")
    output.debug(f"wrote {out}")


def run(args: argparse.Namespace, output: Output) -> int:
    target = Path(args.name).resolve()
    if target.exists() and any(target.iterdir()):
        output.failure(
            exit_code=GENERIC_ERROR,
            error=f"refusing to scaffold into non-empty directory {target}",
        )
        return GENERIC_ERROR

    name = target.name                  # display name (kebab-case ok)
    cname = _c_safe_name(name)          # used in symbols & filenames

    def render(template: str) -> str:
        # Order matters: do the C-safe substitution *first* in case the
        # raw name contains characters that would break C identifiers,
        # then the display name. Today both forms use __NAME__ — pick
        # one per file based on what's safest in context (we use cname
        # everywhere to keep things simple).
        return template.replace("__NAME__", cname)

    files = {
        "CMakeLists.txt":                       render(TOP_CMAKE),
        "main/CMakeLists.txt":                  render(MAIN_CMAKE),
        f"main/{cname}_main.c":                 render(MAIN_C),
        "main/scenes/scene_hello.c":            render(SCENE_HELLO_C),
        "main/scenes/scenes.h":                 SCENES_H,
        "README.md":                            render(README_MD),
        "sdkconfig.defaults":                   SDKCONFIG_DEFAULTS,
        "partitions.csv":                       PARTITIONS_CSV,
        ".gitignore":                           GITIGNORE,
    }

    for relpath, content in files.items():
        _write(target / relpath, content, output)

    output.success(
        {
            "project": str(target),
            "c_name": cname,
            "files": list(files.keys()),
            "harness_hint": (
                str(args.harness_dir) if args.harness_dir
                else "expects ../esp32-harness-showcase/components"
            ),
        },
        human=(
            f"scaffolded {cname} at {target}\n"
            f"  cd {target}\n"
            f"  esp-harness build\n"
            f"  esp-harness flash"
        ),
    )
    return OK
