"""`esp-harness new <name>` — scaffold a fresh ESP-IDF + LVGL project.

Three vendoring modes for aurora-harness:

  --component-source vendor   (default)  copy the whole component into
                                          the new project's components/.
                                          Project is self-contained.
  --component-source link                 EXTRA_COMPONENT_DIRS points at
                                          the monorepo's components/.
                                          Lighter footprint; depends on
                                          the monorepo staying put.
  --component-source depend               write idf_component.yml dep
                                          (caldis/aurora-harness). Needs
                                          the component to be on the
                                          Registry (TBD).

`init` is kept as a back-compat alias for the same command.

Templates live as Python string constants in this file — they're tiny
and changing them shouldn't require a separate template directory.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from esp_harness.exit_codes import GENERIC_ERROR, OK
from esp_harness.output import Output


# Templates use __NAME__ as the substitution marker. The C identifier-safe
# version of the project name is computed in _c_safe_name().

TOP_CMAKE = """\
# Top-level ESP-IDF project file for __NAME__.
#
# aurora-harness vendoring strategy is set when this project was created
# (`esp-harness new --component-source <vendor|link|depend>`):
#
__SOURCE_NOTE__

cmake_minimum_required(VERSION 3.16)

__EXTRA_COMPONENT_DIRS__

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(__NAME__)
"""

MAIN_CMAKE = """\
idf_component_register(
    SRCS
        "__NAME___main.c"
        "scenes/scene_hello.c"
    INCLUDE_DIRS
        "."
        "scenes"
    REQUIRES
        lvgl__lvgl
        aurora-harness
__BSP_REQUIRE__
    PRIV_REQUIRES
        nvs_flash
        esp_timer
)
"""

MAIN_C = """\
/*
 * __NAME___main.c — generated by `esp-harness new`.
 *
 * Wires up: NVS init -> display via BSP -> console protocol ->
 * default harness commands (?stat / scene / tap / swipe / ?dump) ->
 * scene framework -> one demo scene + per-frame fps tick.
 *
 * Replace scene_hello with your own scenes and add peripherals as needed.
 * See ../scenes/scene_hello.c for the smallest scene template.
 */

#include "esp_log.h"
#include "nvs_flash.h"

#include "lvgl.h"
#include "bsp/esp-bsp.h"

#include "harness/console_protocol.h"
#include "harness/scene_framework.h"
#include "harness/default_cmds.h"
#include "scenes/scenes.h"

static const char *TAG = "__NAME__";

static void frame_cb(lv_timer_t *t)
{
    (void)t;
    harness_record_frame();
}

static void on_scene_changed(int idx, const scene_t *current)
{
    /* App's UI chrome listens here. Replace with your own ui_shell sync
     * if you have one. For now just log. */
    if (current) {
        ESP_LOGI(TAG, "scene_changed idx=%d id=%s", idx, current->id);
    }
}

void app_main(void)
{
    /* NVS — needed if you use settings persistence, WiFi PHY cal, etc. */
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }

    /* Bring up display + LVGL via the BSP. */
    bsp_display_start();

    /* Console protocol + the default ?stat / scene / tap / swipe / ?dump set. */
    console_protocol_init();
    harness_default_register();

    /* Build the UI under the LVGL lock. */
    bsp_display_lock(-1);

    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

    scene_fw_init(scr);
    scene_fw_set_change_listener(on_scene_changed);
    scene_fw_register(&scene_hello);

    /* Per-frame tick feeds ?stat's fps field. */
    lv_timer_create(frame_cb, 33, NULL);

    bsp_display_unlock();

    ESP_LOGI(TAG, "ready, %d scene(s)", scene_fw_count());
}
"""

SCENE_HELLO_C = """\
/*
 * scene_hello.c — minimal scene template. Centered label, no animation,
 * no peripheral reads. Copy to scene_<your>.c, edit, register in
 * __NAME___main.c.
 */

#include "harness/scene_framework.h"
#include "lvgl.h"

static void hello_init(scene_t *s, lv_obj_t *parent)
{
    (void)s;
    lv_obj_t *label = lv_label_create(parent);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_22, 0);
    lv_obj_set_style_text_color(label, lv_color_hex(0x8FD9FF), 0);
    lv_label_set_text(label, "Hello, aurora-harness");
    lv_obj_center(label);
}

scene_t scene_hello = {
    .id           = "hello",
    .display_name = "I. Hello",
    .accent       = LV_COLOR_MAKE(0x8F, 0xD9, 0xFF),
    .description  = "Default starter scene; centered label.",
    .tags         = "demo,starter",
    .init         = hello_init,
};
"""

SCENES_H = """\
#pragma once
#include "harness/scene_framework.h"

#ifdef __cplusplus
extern "C" {
#endif

extern scene_t scene_hello;

#ifdef __cplusplus
}
#endif
"""

README_MD = """\
# __NAME__

ESP-IDF + LVGL project generated by `esp-harness new`. Consumes
the [`aurora-harness`](https://github.com/Caldis/esp-harness/tree/master/components/aurora-harness)
component for the console protocol + LVGL scene framework.

## Before your first build — wire in a BSP

This template's `app_main` calls `bsp_display_start()` from the Espressif
BSP convention. **The generated project does NOT include a BSP** — you
need to choose one for your board:

- **Waveshare ESP32-S3-Touch-AMOLED-2.16** — the board Aurora targets.
  The BSP lives at `boards/esp32_s3_touch_amoled_2_16/` in the
  [esp-harness monorepo](https://github.com/Caldis/esp-harness). If
  you scaffolded with `--component-source link`, this is **already
  wired in** via `EXTRA_COMPONENT_DIRS` — skip ahead to "Build".
  If you scaffolded with `vendor`, copy that directory into
  `./components/` and uncomment `esp32_s3_touch_amoled_2_16` in
  `main/CMakeLists.txt`.

- **Another Espressif BSP** — `idf_component.yml` is the standard way;
  e.g. `espressif/esp_bsp` family. Add it to `main/CMakeLists.txt`'s
  REQUIRES.

- **Custom board** — implement `bsp_display_lock()` /
  `bsp_display_unlock()` yourself (the two symbols aurora-harness needs
  per [`bsp_iface.h`](https://github.com/Caldis/esp-harness/blob/master/components/aurora-harness/include/harness/bsp_iface.h))
  plus the LVGL display init. See
  [`PORTING.md`](https://github.com/Caldis/esp-harness/blob/master/components/aurora-harness/PORTING.md).

## Quickstart

```bash
# Verify environment health (incl. ESP-IDF target detection)
esp-harness doctor

# First-time on this machine: set target explicitly if not esp32s3
# idf.py set-target esp32s3

# Build + flash + monitor
esp-harness build
esp-harness flash
esp-harness monitor --seconds 8 --until "ready"

# All-in-one
esp-harness run --until "ready"
```

## Adding a scene

1. Copy `main/scenes/scene_hello.c` to `main/scenes/scene_<name>.c`.
2. Edit + define a `scene_t scene_<name> = { ... };` at the bottom.
3. Add `extern scene_t scene_<name>;` to `main/scenes/scenes.h`.
4. List the new `.c` in `main/CMakeLists.txt` SRCS.
5. `scene_fw_register(&scene_<name>);` in `__NAME___main.c`.

`scene list` over the console now sees it; no further wiring.

## Adding a console command

```c
static int cmd_hello(const console_args_t *args) {
    (void)args;
    console_reply_ok("hi");
    return 0;
}
static const console_cmd_t s_cmd_hello = { "?hello", cmd_hello, "say hi" };

void register_my_cmds(void) {
    console_protocol_register(&s_cmd_hello);
}
```

Call `register_my_cmds()` after `console_protocol_init()` in app_main.

## Where is aurora-harness?

__VENDOR_NOTE__

## What you get

- **Scene framework** — deck of full-screen LVGL views with lifecycle
  hooks. Navigate via touch or `scene <id>` console command.
- **Console protocol** — `OK:` / `ERR:` / `EVT:` framing + multi-line
  payload tags. Universal AI-driveable serial interface.
- **`?stat` command** — fps / heap / scene state as JSON.
- **`?ping` / `?help` / `?reset` / `tap` / `swipe` / `?dump`** built-ins.
- **`harness_toast()`** and **`harness_progress()`** overlay primitives.

Read [`aurora-harness/README.md`](https://github.com/Caldis/esp-harness/blob/master/components/aurora-harness/README.md)
for the full API.

## Where to look when stuck

- Build fails: `esp-harness doctor`
- Console wedged: `esp-harness console --cmd "?ping"`
- Sim diff fails (if you set up sim/): `esp-harness sim diff --save-diffs ./diff-out`
"""

AGENT_MD = """\
# AGENT.md — __NAME__

> AI session onboarding for this project. The full conventions live in
> [esp-harness/AGENT.md](https://github.com/Caldis/esp-harness/blob/master/AGENT.md).
> This file is the project-specific addendum.

## Bootstrap

```bash
esp-harness manifest --json   # what does this project + harness expose?
esp-harness doctor            # env healthy?
```

## Where things go

| Adding | Goes in |
|---|---|
| New scene | `main/scenes/scene_<name>.c` + register in `__NAME___main.c` |
| New peripheral | `main/peripherals/<name>.{c,h}` + REQUIRES in main/CMakeLists.txt |
| New console command | inline in `__NAME___main.c` or a new `main/commands.c` |
| Generic reusable primitive | Open a PR against esp-harness upstream (`components/aurora-harness/`) |

## Don't break the manifest

Every `console_protocol_register()` auto-surfaces in `?help json`. Every
`scene_fw_register()` auto-surfaces in `scene list`. So if you add a
thing, just register it — no separate documentation step.

## Build / run loop

```bash
esp-harness build               # IDF build
esp-harness flash               # esptool flash
esp-harness run --until "X"     # build + flash + monitor with early-exit
esp-harness sim diff            # (if sim/ is set up) visual regression
```

See the root `README.md` for the longer "Quickstart" + the rest.
"""

SDKCONFIG_DEFAULTS = """\
# Recommended starting Kconfig values for an aurora-harness project.
# Conservative defaults; tune per your board.

# Target — explicitly set so `idf.py build` on a fresh clone doesn't
# default to plain `esp32` (which wouldn't have PSRAM and would break
# the LVGL framebuffer allocation below). Change to esp32c6 / esp32p4
# etc. as appropriate AND rerun `idf.py set-target` before first build.
CONFIG_IDF_TARGET="esp32s3"
CONFIG_IDF_TARGET_ESP32S3=y

CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=y
CONFIG_COMPILER_OPTIMIZATION_PERF=y

# LVGL typically needs PSRAM for full-screen buffers.
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_SPEED_80M=y

# console_protocol prefers USB-Serial-JTAG (no extra wires on most dev kits).
CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=y

CONFIG_NVS_ENABLED=y

# aurora-harness ships a `?dump` screenshot command that uses
# lv_snapshot_take_to_draw_buf — that LVGL feature is OFF by default.
# Without this, `components/aurora-harness/src/screenshot.c` fails to
# compile with `implicit declaration of function 'lv_snapshot_take_to_draw_buf'`.
CONFIG_LV_USE_SNAPSHOT=y

# LVGL's libc-malloc adapters (we use them in Aurora; keeping the
# defaults here means PSRAM is the malloc backend automatically).
CONFIG_LV_USE_CLIB_MALLOC=y
CONFIG_LV_USE_CLIB_STRING=y
CONFIG_LV_USE_CLIB_SPRINTF=y

# LVGL OS layer: aurora-harness assumes FreeRTOS-backed mutexes for
# inter-task safety. Default is "none" which breaks lv_async_call
# correctness in console-driven flows.
CONFIG_LV_OS_FREERTOS=y

# 16 MB flash with two OTA slots is the Aurora default. Adjust
# partitions.csv to match if your board has 4 MB / 8 MB flash.
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

# Bigger fonts for the scene_hello label. LVGL's Kconfig only ships
# montserrat_14 by default; enable 22 explicitly so the template's
# label renders at a readable size on a 466×466 screen.
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_22=y
"""

PARTITIONS_CSV = """\
# Standard factory layout. Bump app size if your binary grows past 6 MB
# or add OTA partitions when you wire up esp_https_ota.
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs,      data, nvs,      0x9000,   0x6000,
phy_init, data, phy,      0xf000,   0x1000,
factory,  app,  factory,  0x10000,  6M,
"""

GITIGNORE = """\
build/
.vscode/
sdkconfig
sdkconfig.old
managed_components/
dependencies.lock
__pycache__/
*.pyc
"""


def add_subparser(sub, add_common_flags) -> None:
    p = sub.add_parser(
        "new",
        help="Scaffold a fresh ESP-IDF + LVGL project consuming aurora-harness.",
        description=(
            "Creates a directory <name>/ with a minimal app_main, a 'Hello' "
            "scene, and CMakeLists wiring aurora-harness via one of three "
            "vendoring strategies (--component-source vendor|link|depend)."
        ),
    )
    p.add_argument("name", help="Project directory to create. Must not exist yet.")
    p.add_argument(
        "--component-source", "--source",
        choices=("vendor", "link", "depend"),
        default="link",
        help=(
            "How the new project consumes aurora-harness: "
            "link (default) points EXTRA_COMPONENT_DIRS at the monorepo "
            "and wires in the Waveshare BSP automatically — builds out "
            "of the box; "
            "vendor copies aurora-harness into the project for "
            "self-containment (but you must wire a BSP yourself); "
            "depend writes an idf_component.yml dependency (requires "
            "the component to be published to the Component Registry)."
        ),
    )
    p.add_argument(
        "--harness-root", type=Path, default=None,
        help="Override the monorepo root (where components/aurora-harness/ lives). "
             "Default: auto-detect from the toolkit's install location.",
    )
    add_common_flags(p)


def _c_safe_name(name: str) -> str:
    """Make a project name safe for C identifiers AND a CMake target.
    Replace non-alphanum with `_`; prefix a leading underscore if the
    name starts with a digit (so `1app` → `_1app`, since C identifiers
    and some CMake targets reject digit-leading names)."""
    out = "".join(c if c.isalnum() else "_" for c in name)
    if out and out[0].isdigit():
        out = "_" + out
    return out or "_unnamed"


def _pinnable_version() -> str:
    """Toolkit's `MAJOR.MINOR.0` form, suitable for `^X.Y.0` registry
    pins. We bind the depend-mode aurora-harness pin to the toolkit's
    current release line so the literal doesn't go stale across
    releases. `^1.7.0` lets the consumer's registry pull any 1.7.x
    (and per semver any 1.x ≥ 1.7) without an upstream code change.
    """
    from esp_harness import __version__
    parts = __version__.split(".")
    major = parts[0] if len(parts) >= 1 else "1"
    minor = parts[1] if len(parts) >= 2 else "0"
    return f"{major}.{minor}.0"


def _detect_harness_root(override: Path | None) -> Path | None:
    """Walk up from this file to find the monorepo root."""
    if override:
        return override if (override / "components" / "aurora-harness").exists() else None
    toolkit_root  = Path(__file__).resolve().parents[3]
    monorepo_root = toolkit_root.parents[1]
    if (monorepo_root / "components" / "aurora-harness").exists():
        return monorepo_root
    return None


def _write(out: Path, content: str, output: Output) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8", newline="\n")
    output.debug(f"wrote {out}")


def run(args: argparse.Namespace, output: Output) -> int:
    target = Path(args.name).resolve()
    if target.exists() and any(target.iterdir()):
        output.failure(
            exit_code=GENERIC_ERROR,
            error=f"refusing to scaffold into non-empty directory {target}",
        )
        return GENERIC_ERROR

    cname = _c_safe_name(target.name)
    source = args.component_source

    harness_root = _detect_harness_root(args.harness_root)
    if source in ("vendor", "link") and not harness_root:
        output.failure(
            exit_code=GENERIC_ERROR,
            error=(
                "Cannot find esp-harness monorepo (no components/aurora-harness/ "
                "in expected location). Pass --harness-root /path/to/esp-harness, "
                "or use --component-source depend (registry, requires publish)."
            ),
        )
        return GENERIC_ERROR

    # Plan the CMake fragments + README note per source mode.
    if source == "vendor":
        source_note = (
            "#   vendor: components/aurora-harness/ is copied into ./components/.\n"
            "#           This project is self-contained — no external deps.\n"
            "#           Re-vendor by re-running `esp-harness new` against a newer\n"
            "#           harness clone, or copy in updates manually."
        )
        extra_dirs = (
            "# components/ already contains aurora-harness (vendored). "
            "ESP-IDF auto-discovers components in ./components/, so no\n"
            "# EXTRA_COMPONENT_DIRS needed.\n"
            "# If you add a board BSP from the esp-harness monorepo, append:\n"
            "#   list(APPEND EXTRA_COMPONENT_DIRS /path/to/esp-harness/boards)"
        )
        # vendor mode: BSP NOT bundled. User must add it themselves before
        # the project builds. Leave the line commented so it's visible.
        bsp_require = (
            "        # Add your board's BSP component here. e.g. uncomment\n"
            "        # for the Waveshare AMOLED 2.16:\n"
            "        # esp32_s3_touch_amoled_2_16"
        )
        vendor_note = (
            "This project **vendored** aurora-harness into `components/aurora-harness/`. "
            "It's self-contained — no external clone needed. To update, replace the "
            "vendored copy with a newer one from "
            "[esp-harness](https://github.com/Caldis/esp-harness)."
        )
    elif source == "link":
        source_note = (
            f"#   link: EXTRA_COMPONENT_DIRS points at the monorepo at\n"
            f"#         {harness_root}. Lighter footprint than vendor; depends\n"
            f"#         on that path remaining valid."
        )
        extra_dirs = (
            f"# ESP_HARNESS_ROOT can be overridden by env var or -D on the\n"
            f"# build command; defaults to the path captured at scaffold time.\n"
            f"if(NOT DEFINED ESP_HARNESS_ROOT)\n"
            f"    if(DEFINED ENV{{ESP_HARNESS_ROOT}})\n"
            f"        set(ESP_HARNESS_ROOT \"$ENV{{ESP_HARNESS_ROOT}}\")\n"
            f"    else()\n"
            f"        set(ESP_HARNESS_ROOT \"{harness_root.as_posix()}\")\n"
            f"    endif()\n"
            f"endif()\n"
            f"list(APPEND EXTRA_COMPONENT_DIRS\n"
            f"    ${{ESP_HARNESS_ROOT}}/components\n"
            f"    ${{ESP_HARNESS_ROOT}}/boards\n"
            f")"
        )
        # link mode: monorepo's boards/ is on EXTRA_COMPONENT_DIRS, so the
        # Waveshare BSP IS available — wire it in by default so the project
        # builds out of the box on that board.
        bsp_require = (
            "        # Waveshare AMOLED 2.16 (Aurora's board) — pulled from\n"
            "        # ${ESP_HARNESS_ROOT}/boards/ via EXTRA_COMPONENT_DIRS.\n"
            "        # Replace with your own BSP if targeting a different board.\n"
            "        esp32_s3_touch_amoled_2_16"
        )
        vendor_note = (
            f"This project **links** aurora-harness from `{harness_root}`. "
            "If you move the esp-harness clone, update `ESP_HARNESS_ROOT` "
            "in the top-level CMakeLists.txt accordingly."
        )
    else:  # depend
        source_note = (
            "#   depend: aurora-harness pulled via idf_component.yml from the\n"
            "#           ESP-IDF Component Registry. Requires `caldis/aurora-harness`\n"
            "#           to be published (status: not yet, as of v1.5)."
        )
        extra_dirs = (
            "# aurora-harness fetched via the component manager — see\n"
            "# main/idf_component.yml. No EXTRA_COMPONENT_DIRS needed."
        )
        bsp_require = (
            "        # Add your board's BSP component here. e.g. via\n"
            "        # idf_component.yml or EXTRA_COMPONENT_DIRS."
        )
        vendor_note = (
            "This project **depends** on aurora-harness via the ESP-IDF "
            "Component Registry. `idf.py reconfigure` will fetch it into "
            "`managed_components/`. Pin the version in `main/idf_component.yml`."
        )

    top_cmake = (TOP_CMAKE
                 .replace("__NAME__", cname)
                 .replace("__SOURCE_NOTE__", source_note)
                 .replace("__EXTRA_COMPONENT_DIRS__", extra_dirs))

    main_cmake = (MAIN_CMAKE
                  .replace("__NAME__", cname)
                  .replace("__BSP_REQUIRE__", bsp_require))

    files: dict[str, str] = {
        "CMakeLists.txt":                       top_cmake,
        "main/CMakeLists.txt":                  main_cmake,
        f"main/{cname}_main.c":                 MAIN_C.replace("__NAME__", cname),
        "main/scenes/scene_hello.c":            SCENE_HELLO_C.replace("__NAME__", cname),
        "main/scenes/scenes.h":                 SCENES_H,
        "README.md":                            (README_MD
                                                  .replace("__NAME__", cname)
                                                  .replace("__VENDOR_NOTE__", vendor_note)),
        "AGENT.md":                             AGENT_MD.replace("__NAME__", cname),
        "sdkconfig.defaults":                   SDKCONFIG_DEFAULTS,
        "partitions.csv":                       PARTITIONS_CSV,
        ".gitignore":                           GITIGNORE,
    }
    if source == "depend":
        # Write an idf_component.yml so the component manager fetches the dep.
        files["main/idf_component.yml"] = (
            "## Dependencies fetched by the IDF Component Manager.\n"
            "## `idf.py reconfigure` populates managed_components/.\n"
            "\n"
            "dependencies:\n"
            "  lvgl/lvgl: \"^9.0\"\n"
            # Pin to the toolkit's current major+minor — once aurora-harness
            # is published to the registry, the dep version tracks the
            # toolkit's release line automatically. Avoids the stale
            # `^1.5.0` literal that lingered through 1.7.x.
            f"  caldis/aurora-harness: \"^{_pinnable_version()}\"\n"
            "  ## Add your board's BSP component dep here.\n"
        )

    for relpath, content in files.items():
        _write(target / relpath, content, output)

    # vendor mode: actually copy the component into the new project's components/
    if source == "vendor":
        src_comp = harness_root / "components" / "aurora-harness"
        dst_comp = target / "components" / "aurora-harness"
        try:
            shutil.copytree(src_comp, dst_comp,
                            ignore=shutil.ignore_patterns("build", "managed_components",
                                                          "__pycache__"))
            output.info(f"vendored: {src_comp} -> {dst_comp}")
        except Exception as e:
            output.failure(exit_code=GENERIC_ERROR,
                           error=f"failed to copy aurora-harness into project: {e}")
            return GENERIC_ERROR

    # Build hint varies by source mode — `link` builds cleanly out of
    # the box (the default), the other two need user follow-up before
    # `esp-harness build` will succeed. Telling the user to build
    # immediately when we know it'll fail is a hostile UX.
    if source == "link":
        next_steps = (
            f"scaffolded {cname} at {target} (source: link — BSP auto-wired)\n"
            f"  cd {target}\n"
            f"  esp-harness build         # ≈ 60s clean build\n"
            f"  esp-harness flash"
        )
        next_steps_json = "build_ready"
    elif source == "vendor":
        next_steps = (
            f"scaffolded {cname} at {target} (source: vendor — BSP NOT bundled)\n"
            f"  ! Before `esp-harness build` will work, you must add a\n"
            f"  ! board BSP. The generated README.md's \"Before your first\n"
            f"  ! build\" section lists the three options. Quickest path:\n"
            f"  cp -r {harness_root}\\boards\\esp32_s3_touch_amoled_2_16\n"
            f"        {target}\\components\\\n"
            f"  # then uncomment the BSP line in {target}\\main\\CMakeLists.txt"
        )
        next_steps_json = "needs_bsp_wiring"
    else:  # depend
        next_steps = (
            f"scaffolded {cname} at {target} (source: depend — registry)\n"
            f"  ! aurora-harness is NOT YET published to the ESP-IDF\n"
            f"  ! Component Registry (status: scheduled for v2.0). Until\n"
            f"  ! then, `esp-harness build` will fail with `Version solving\n"
            f"  ! failed`. Use --component-source link or vendor instead."
        )
        next_steps_json = "registry_not_published"

    output.success(
        {
            "project": str(target),
            "c_name": cname,
            "component_source": source,
            "harness_root": str(harness_root) if harness_root else None,
            "files": list(files.keys()),
            "next_step": next_steps_json,
        },
        human=next_steps,
    )
    return OK
