"""`esp-harness new <name>` — scaffold a fresh ESP-IDF + LVGL project.

Three vendoring modes for aurora-harness:

  --component-source vendor   (default)  copy the whole component into
                                          the new project's components/.
                                          Project is self-contained.
  --component-source link                 EXTRA_COMPONENT_DIRS points at
                                          the monorepo's components/.
                                          Lighter footprint; depends on
                                          the monorepo staying put.
  --component-source depend               write idf_component.yml dep
                                          (caldis/aurora-harness). Needs
                                          the component to be on the
                                          Registry (TBD).

`init` is kept as a back-compat alias for the same command.

Templates live as Python string constants in this file — they're tiny
and changing them shouldn't require a separate template directory.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from esp_harness.exit_codes import GENERIC_ERROR, OK
from esp_harness.output import Output


# Templates use __NAME__ as the substitution marker. The C identifier-safe
# version of the project name is computed in _c_safe_name().

TOP_CMAKE = """\
# Top-level ESP-IDF project file for __NAME__.
#
# aurora-harness vendoring strategy is set when this project was created
# (`esp-harness new --component-source <vendor|link|depend>`):
#
__SOURCE_NOTE__

cmake_minimum_required(VERSION 3.16)

__EXTRA_COMPONENT_DIRS__

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(__NAME__)
"""

MAIN_CMAKE = """\
idf_component_register(
    SRCS
        "__NAME___main.c"
        "scenes/scene_hello.c"
    INCLUDE_DIRS
        "."
        "scenes"
    REQUIRES
        lvgl__lvgl
        aurora-harness
        # Add your board's BSP component here. Aurora demo uses:
        # esp32_s3_touch_amoled_2_16
    PRIV_REQUIRES
        nvs_flash
        esp_timer
)
"""

MAIN_C = """\
/*
 * __NAME___main.c — generated by `esp-harness new`.
 *
 * Wires up: NVS init -> display via BSP -> console protocol ->
 * default harness commands (?stat / scene / tap / swipe / ?dump) ->
 * scene framework -> one demo scene + per-frame fps tick.
 *
 * Replace scene_hello with your own scenes and add peripherals as needed.
 * See ../scenes/scene_hello.c for the smallest scene template.
 */

#include "esp_log.h"
#include "nvs_flash.h"

#include "lvgl.h"
#include "bsp/esp-bsp.h"

#include "harness/console_protocol.h"
#include "harness/scene_framework.h"
#include "harness/default_cmds.h"
#include "scenes/scenes.h"

static const char *TAG = "__NAME__";

static void frame_cb(lv_timer_t *t)
{
    (void)t;
    harness_record_frame();
}

static void on_scene_changed(int idx, const scene_t *current)
{
    /* App's UI chrome listens here. Replace with your own ui_shell sync
     * if you have one. For now just log. */
    if (current) {
        ESP_LOGI(TAG, "scene_changed idx=%d id=%s", idx, current->id);
    }
}

void app_main(void)
{
    /* NVS — needed if you use settings persistence, WiFi PHY cal, etc. */
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }

    /* Bring up display + LVGL via the BSP. */
    bsp_display_start();

    /* Console protocol + the default ?stat / scene / tap / swipe / ?dump set. */
    console_protocol_init();
    harness_default_register();

    /* Build the UI under the LVGL lock. */
    bsp_display_lock(-1);

    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

    scene_fw_init(scr);
    scene_fw_set_change_listener(on_scene_changed);
    scene_fw_register(&scene_hello);

    /* Per-frame tick feeds ?stat's fps field. */
    lv_timer_create(frame_cb, 33, NULL);

    bsp_display_unlock();

    ESP_LOGI(TAG, "ready, %d scene(s)", scene_fw_count());
}
"""

SCENE_HELLO_C = """\
/*
 * scene_hello.c — minimal scene template. Centered label, no animation,
 * no peripheral reads. Copy to scene_<your>.c, edit, register in
 * __NAME___main.c.
 */

#include "harness/scene_framework.h"
#include "lvgl.h"

static void hello_init(scene_t *s, lv_obj_t *parent)
{
    (void)s;
    lv_obj_t *label = lv_label_create(parent);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_22, 0);
    lv_obj_set_style_text_color(label, lv_color_hex(0x8FD9FF), 0);
    lv_label_set_text(label, "Hello, aurora-harness");
    lv_obj_center(label);
}

scene_t scene_hello = {
    .id           = "hello",
    .display_name = "I. Hello",
    .accent       = LV_COLOR_MAKE(0x8F, 0xD9, 0xFF),
    .description  = "Default starter scene; centered label.",
    .tags         = "demo,starter",
    .init         = hello_init,
};
"""

SCENES_H = """\
#pragma once
#include "harness/scene_framework.h"

#ifdef __cplusplus
extern "C" {
#endif

extern scene_t scene_hello;

#ifdef __cplusplus
}
#endif
"""

README_MD = """\
# __NAME__

ESP-IDF + LVGL project generated by `esp-harness new`. Consumes
the [`aurora-harness`](https://github.com/Caldis/esp-harness/tree/master/components/aurora-harness)
component for the console protocol + LVGL scene framework.

## Quickstart

```bash
# Verify environment health
esp-harness doctor

# Build + flash + monitor
esp-harness build
esp-harness flash
esp-harness monitor --seconds 8 --until "ready"

# All-in-one
esp-harness run --until "ready"
```

## Adding a scene

1. Copy `main/scenes/scene_hello.c` to `main/scenes/scene_<name>.c`.
2. Edit + define a `scene_t scene_<name> = { ... };` at the bottom.
3. Add `extern scene_t scene_<name>;` to `main/scenes/scenes.h`.
4. List the new `.c` in `main/CMakeLists.txt` SRCS.
5. `scene_fw_register(&scene_<name>);` in `__NAME___main.c`.

`scene list` over the console now sees it; no further wiring.

## Adding a console command

```c
static int cmd_hello(const console_args_t *args) {
    (void)args;
    console_reply_ok("hi");
    return 0;
}
static const console_cmd_t s_cmd_hello = { "?hello", cmd_hello, "say hi" };

void register_my_cmds(void) {
    console_protocol_register(&s_cmd_hello);
}
```

Call `register_my_cmds()` after `console_protocol_init()` in app_main.

## Where is aurora-harness?

__VENDOR_NOTE__

## What you get

- **Scene framework** — deck of full-screen LVGL views with lifecycle
  hooks. Navigate via touch or `scene <id>` console command.
- **Console protocol** — `OK:` / `ERR:` / `EVT:` framing + multi-line
  payload tags. Universal AI-driveable serial interface.
- **`?stat` command** — fps / heap / scene state as JSON.
- **`?ping` / `?help` / `?reset` / `tap` / `swipe` / `?dump`** built-ins.
- **`harness_toast()`** and **`harness_progress()`** overlay primitives.

Read [`aurora-harness/README.md`](https://github.com/Caldis/esp-harness/blob/master/components/aurora-harness/README.md)
for the full API.

## Where to look when stuck

- Build fails: `esp-harness doctor`
- Console wedged: `esp-harness console --cmd "?ping"`
- Sim diff fails (if you set up sim/): `esp-harness sim diff --save-diffs ./diff-out`
"""

AGENT_MD = """\
# AGENT.md — __NAME__

> AI session onboarding for this project. The full conventions live in
> [esp-harness/AGENT.md](https://github.com/Caldis/esp-harness/blob/master/AGENT.md).
> This file is the project-specific addendum.

## Bootstrap

```bash
esp-harness manifest --json   # what does this project + harness expose?
esp-harness doctor            # env healthy?
```

## Where things go

| Adding | Goes in |
|---|---|
| New scene | `main/scenes/scene_<name>.c` + register in `__NAME___main.c` |
| New peripheral | `main/peripherals/<name>.{c,h}` + REQUIRES in main/CMakeLists.txt |
| New console command | inline in `__NAME___main.c` or a new `main/commands.c` |
| Generic reusable primitive | Open a PR against esp-harness upstream (`components/aurora-harness/`) |

## Don't break the manifest

Every `console_protocol_register()` auto-surfaces in `?help json`. Every
`scene_fw_register()` auto-surfaces in `scene list`. So if you add a
thing, just register it — no separate documentation step.

## Build / run loop

```bash
esp-harness build               # IDF build
esp-harness flash               # esptool flash
esp-harness run --until "X"     # build + flash + monitor with early-exit
esp-harness sim diff            # (if sim/ is set up) visual regression
```

See the root `README.md` for the longer "Quickstart" + the rest.
"""

SDKCONFIG_DEFAULTS = """\
# Recommended starting Kconfig values for an aurora-harness project.
# Conservative defaults; tune per your board.

CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=y
CONFIG_COMPILER_OPTIMIZATION_PERF=y

# LVGL typically needs PSRAM for full-screen buffers.
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_SPEED_80M=y

# console_protocol prefers USB-Serial-JTAG (no extra wires on most dev kits).
CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=y

CONFIG_NVS_ENABLED=y
"""

PARTITIONS_CSV = """\
# Standard factory layout. Bump app size if your binary grows past 6 MB
# or add OTA partitions when you wire up esp_https_ota.
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs,      data, nvs,      0x9000,   0x6000,
phy_init, data, phy,      0xf000,   0x1000,
factory,  app,  factory,  0x10000,  6M,
"""

GITIGNORE = """\
build/
.vscode/
sdkconfig
sdkconfig.old
managed_components/
dependencies.lock
__pycache__/
*.pyc
"""


def add_subparser(sub, add_common_flags) -> None:
    p = sub.add_parser(
        "new",
        help="Scaffold a fresh ESP-IDF + LVGL project consuming aurora-harness.",
        description=(
            "Creates a directory <name>/ with a minimal app_main, a 'Hello' "
            "scene, and CMakeLists wiring aurora-harness via one of three "
            "vendoring strategies (--component-source vendor|link|depend)."
        ),
    )
    p.add_argument("name", help="Project directory to create. Must not exist yet.")
    p.add_argument(
        "--component-source", "--source",
        choices=("vendor", "link", "depend"),
        default="vendor",
        help=(
            "How the new project consumes aurora-harness: "
            "vendor (default) copies the component into the project; "
            "link points EXTRA_COMPONENT_DIRS at the monorepo; "
            "depend writes an idf_component.yml dependency (requires "
            "the component to be published to the Component Registry)."
        ),
    )
    p.add_argument(
        "--harness-root", type=Path, default=None,
        help="Override the monorepo root (where components/aurora-harness/ lives). "
             "Default: auto-detect from the toolkit's install location.",
    )
    add_common_flags(p)


def _c_safe_name(name: str) -> str:
    """Make a project name safe for C identifiers: replace -+./ with _."""
    return "".join(c if c.isalnum() else "_" for c in name)


def _detect_harness_root(override: Path | None) -> Path | None:
    """Walk up from this file to find the monorepo root."""
    if override:
        return override if (override / "components" / "aurora-harness").exists() else None
    toolkit_root  = Path(__file__).resolve().parents[3]
    monorepo_root = toolkit_root.parents[1]
    if (monorepo_root / "components" / "aurora-harness").exists():
        return monorepo_root
    return None


def _write(out: Path, content: str, output: Output) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8", newline="\n")
    output.debug(f"wrote {out}")


def run(args: argparse.Namespace, output: Output) -> int:
    target = Path(args.name).resolve()
    if target.exists() and any(target.iterdir()):
        output.failure(
            exit_code=GENERIC_ERROR,
            error=f"refusing to scaffold into non-empty directory {target}",
        )
        return GENERIC_ERROR

    cname = _c_safe_name(target.name)
    source = args.component_source

    harness_root = _detect_harness_root(args.harness_root)
    if source in ("vendor", "link") and not harness_root:
        output.failure(
            exit_code=GENERIC_ERROR,
            error=(
                "Cannot find esp-harness monorepo (no components/aurora-harness/ "
                "in expected location). Pass --harness-root /path/to/esp-harness, "
                "or use --component-source depend (registry, requires publish)."
            ),
        )
        return GENERIC_ERROR

    # Plan the CMake fragments + README note per source mode.
    if source == "vendor":
        source_note = (
            "#   vendor: components/aurora-harness/ is copied into ./components/.\n"
            "#           This project is self-contained — no external deps.\n"
            "#           Re-vendor by re-running `esp-harness new` against a newer\n"
            "#           harness clone, or copy in updates manually."
        )
        extra_dirs = (
            "# components/ already contains aurora-harness (vendored). "
            "ESP-IDF auto-discovers components in ./components/, so no\n"
            "# EXTRA_COMPONENT_DIRS needed.\n"
            "# If you add a board BSP from the esp-harness monorepo, append:\n"
            "#   list(APPEND EXTRA_COMPONENT_DIRS /path/to/esp-harness/boards)"
        )
        vendor_note = (
            "This project **vendored** aurora-harness into `components/aurora-harness/`. "
            "It's self-contained — no external clone needed. To update, replace the "
            "vendored copy with a newer one from "
            "[esp-harness](https://github.com/Caldis/esp-harness)."
        )
    elif source == "link":
        source_note = (
            f"#   link: EXTRA_COMPONENT_DIRS points at the monorepo at\n"
            f"#         {harness_root}. Lighter footprint than vendor; depends\n"
            f"#         on that path remaining valid."
        )
        extra_dirs = (
            f"if(NOT DEFINED ESP_HARNESS_ROOT)\n"
            f"    set(ESP_HARNESS_ROOT \"{harness_root.as_posix()}\")\n"
            f"endif()\n"
            f"list(APPEND EXTRA_COMPONENT_DIRS\n"
            f"    ${{ESP_HARNESS_ROOT}}/components\n"
            f"    ${{ESP_HARNESS_ROOT}}/boards\n"
            f")"
        )
        vendor_note = (
            f"This project **links** aurora-harness from `{harness_root}`. "
            "If you move the esp-harness clone, update `ESP_HARNESS_ROOT` "
            "in the top-level CMakeLists.txt accordingly."
        )
    else:  # depend
        source_note = (
            "#   depend: aurora-harness pulled via idf_component.yml from the\n"
            "#           ESP-IDF Component Registry. Requires `caldis/aurora-harness`\n"
            "#           to be published (status: not yet, as of v1.5)."
        )
        extra_dirs = (
            "# aurora-harness fetched via the component manager — see\n"
            "# main/idf_component.yml. No EXTRA_COMPONENT_DIRS needed."
        )
        vendor_note = (
            "This project **depends** on aurora-harness via the ESP-IDF "
            "Component Registry. `idf.py reconfigure` will fetch it into "
            "`managed_components/`. Pin the version in `main/idf_component.yml`."
        )

    top_cmake = (TOP_CMAKE
                 .replace("__NAME__", cname)
                 .replace("__SOURCE_NOTE__", source_note)
                 .replace("__EXTRA_COMPONENT_DIRS__", extra_dirs))

    files: dict[str, str] = {
        "CMakeLists.txt":                       top_cmake,
        "main/CMakeLists.txt":                  MAIN_CMAKE.replace("__NAME__", cname),
        f"main/{cname}_main.c":                 MAIN_C.replace("__NAME__", cname),
        "main/scenes/scene_hello.c":            SCENE_HELLO_C.replace("__NAME__", cname),
        "main/scenes/scenes.h":                 SCENES_H,
        "README.md":                            (README_MD
                                                  .replace("__NAME__", cname)
                                                  .replace("__VENDOR_NOTE__", vendor_note)),
        "AGENT.md":                             AGENT_MD.replace("__NAME__", cname),
        "sdkconfig.defaults":                   SDKCONFIG_DEFAULTS,
        "partitions.csv":                       PARTITIONS_CSV,
        ".gitignore":                           GITIGNORE,
    }
    if source == "depend":
        # Write an idf_component.yml so the component manager fetches the dep.
        files["main/idf_component.yml"] = (
            "## Dependencies fetched by the IDF Component Manager.\n"
            "## `idf.py reconfigure` populates managed_components/.\n"
            "\n"
            "dependencies:\n"
            "  lvgl/lvgl: \"^9.0\"\n"
            "  caldis/aurora-harness: \"^1.5.0\"\n"
            "  ## Add your board's BSP component dep here.\n"
        )

    for relpath, content in files.items():
        _write(target / relpath, content, output)

    # vendor mode: actually copy the component into the new project's components/
    if source == "vendor":
        src_comp = harness_root / "components" / "aurora-harness"
        dst_comp = target / "components" / "aurora-harness"
        try:
            shutil.copytree(src_comp, dst_comp,
                            ignore=shutil.ignore_patterns("build", "managed_components",
                                                          "__pycache__"))
            output.info(f"vendored: {src_comp} -> {dst_comp}")
        except Exception as e:
            output.failure(exit_code=GENERIC_ERROR,
                           error=f"failed to copy aurora-harness into project: {e}")
            return GENERIC_ERROR

    output.success(
        {
            "project": str(target),
            "c_name": cname,
            "component_source": source,
            "harness_root": str(harness_root) if harness_root else None,
            "files": list(files.keys()),
        },
        human=(
            f"scaffolded {cname} at {target} (source: {source})\n"
            f"  cd {target}\n"
            f"  esp-harness build\n"
            f"  esp-harness flash"
        ),
    )
    return OK
